name: Build and Push Landing Docker Image

on:
  push:
    branches: [master]
    paths:
      - 'frontend/**'

jobs:
  build-landing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build & push
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/crm-landing:latest
